image: "ruby:2.3"

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - apt-get update -qq && apt-get install -y -qq build-essential sqlite3 libsqlite3-dev python2.7 python-pip python-dev ipython ipython-notebook
  - curl -sL https://deb.nodesource.com/setup_6.x | bash -
  - apt-get install -y nodejs
  - node --version
  - npm --version
  - npm install --global yarn
  - yarn --version
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc 
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"
  - yarn

test:
  script:
    - bundle exec rails test

