language: ruby
rvm:
env: 
  - RAILS_ENV=test
script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate --trace RAILS_ENV=development
  - bundle exec rake db:migrate --trace RAILS_ENV=test
  - bundle exec rails db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake test