defaults: &defaults
  python_cmd:  python
  jupyter_cmd: jupyter
  openvsp_cmd: vspscript
  thrift_cmd: thrift

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  python_cmd:  /d/rlafage/opt/miniconda3/bin/python
  jupyter_cmd: /d/rlafage/opt/miniconda3/bin/jupyter
  openvsp_cmd: /tmp_user/rdri206h/rlafage/OpenVSP-3.13.3-Linux/vspscript
  
production:
  python_cmd:  /dtis-app/miniconda2/envs/whatsopt/bin/python
  jupyter_cmd: /dtis-app/miniconda2/envs/whatsopt/bin/jupyter
  openvsp_cmd: /dtis-app/OpenVSP-3.13.3/vspscript

