defaults: &defaults
  python_cmd:  python
  jupyter_cmd: jupyter
  openvsp_cmd: vspscript

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  python_cmd:  /tmp_user/rdri206h/rlafage/anaconda2/bin/python
  jupyter_cmd: /tmp_user/rdri206h/rlafage/anaconda2/bin/jupyter
  openvsp_cmd: /tmp_user/rdri206h/rlafage/OpenVSP-3.13.3-Linux/vspscript
  
production:
  python_cmd:  /dtis-app/miniconda2/envs/whatsopt/bin/python
  jupyter_cmd: /dtis-app/miniconda2/envs/whatsopt/bin/jupyter
  openvsp_cmd: /dtis-app/OpenVSP-3.13.3-Linux/vspscript
  