defaults: &defaults
  intranet:    <%= !ENV['WHATSOPT_INTERNET'] %>
  python_cmd:  python
  openvsp_cmd: vspscript
  thrift_cmd:  thrift

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  intranet:    <%= !ENV['WHATSOPT_INTERNET'] %>
  python_cmd:  /d/rlafage/opt/miniconda3/bin/python
  openvsp_cmd: /tmp_user/rdri206h/rlafage/OpenVSP-3.13.3-Linux/vspscript
  
production:
  intranet:    <%= !ENV['WHATSOPT_INTERNET'] %>
  python_cmd:  /dtis-app/whatsopt-deps/miniconda3/bin/python
  openvsp_cmd: /dtis-app/whatsopt-deps/OpenVSP-3.13.3/vspscript
  thrift_cmd:  /dtis-app/whatsopt-deps/thrift-0.11.0/bin/thrift

